version: 2

sources:
  - name: shop
    schema: raw
    tables:
      - name: products
        identifier: SHOP

      - name: dates
        identifier: SHOP

      - name: customers
        identifier: SHOP
        loaded_at_field: timestamp_column
        freshness:
          warn_after: {count: 1, period: hour}
          error_after: {count: 24, period: hour}